### PR TITLE
bugfix: sd rescan and load on triple click

### PR DESCRIPTION
**Pull request by tsctrl**
file.path() not working on platform = espressif32

### CODE REVIEW

**Comment by Edzelf** [comment]
Latest version allows platform = espressif32 as well as "espressif32@3.1.0".

**Comment by tsctrl** [comment]
@Edzelf 
changes to get full path is added on arduino version 2.0 or pio v4.0.0 only. old file.name() to get full path will not work anymore

minimum version is v4.0.0
https://github.com/platformio/platform-espressif32/releases/tag/v4.0.0

arduino version 2.0.3 was release few week ago, definitely more stable and less time to figure problem. and still under espressif support. i would suggest radio v2 to be updated to the latest arduino 2.0.3 version to allow esp32 s3 support for new design as esp32 v1 already very old. there is no changes required on the esp radio end. this for hope to support the future existence on this beloved internet radio apps. 👯‍♂️

**Comment by tsctrl** [comment]
Hi @Edzelf 

for this recent change:
#ifdef DEC_HELIX_INT
  #if ESP_ARDUINO_VERSION_MAJOR >= 2
    #error Internal DAC will not work in this version of the platform.  Use espressif32@3.1.0.
  #endif
#endif

i did not try but internal dac should work on arduino 2.0.3 as mentioned here:
https://github.com/espressif/arduino-esp32/issues/5938

**Comment by tsctrl** [comment]
closing this, as per solution added. thanks @Edzelf

**Pull request closed without merging**
